{
    "CVSSv3": {
        "CVSS": "3.1",
        "attackVector": "NETWORK",
        "attackComplexity": "LOW",
        "privilegesRequired": "NONE",
        "userInteraction": "NONE",
        "scope": "UNCHANGED",
        "confidentiality": "LOW",
        "integrity": "NONE",
        "availability": "NONE"
    },
    "credit": [
        "Unknown"
    ],
    "cvssDetails": [],
    "cvssScore": 5.3,
    "disclosureTime": "2023-12-01 06:27:52",
    "epssDetails": null,
    "exploitMaturity": "Not Defined",
    "id": "SNYK-PYTHON-BIGDL-6133269",
    "identifiers": {
        "CVE": [],
        "CWE": [
            "CWE-326"
        ],
        "PVE": [
            "PVE-2023-62334"
        ]
    },
    "language": "python",
    "malicious": false,
    "packageManager": "pip",
    "publicationTime": "2023-12-20 15:58:53",
    "remediation": "Upgrade bigdl to version 2.4.0 or higher. ",
    "severity": "medium",
    "socialTrendAlert": false,
    "title": "Inadequate Encryption Strength",
    "vulnDescription": {
        "Overview": "bigdl is a Building Large-Scale AI Applications for Distributed Big Data Affected versions of this package are vulnerable to Inadequate Encryption Strength due to the usage of an insecure DES3 encryption algorithm. "
    },
    "source_code": []
}